name: Renovate
on:
  schedule:
    - cron: '0/3 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
    # - name: report back
    #   1. Use GH api to get results from renovate (see get-info.sh)
    #   2. Push results to our own datastore
    #   
